[project]
name = "alphakyoen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numba>=0.64.0",
    "numpy>=2.4.2",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
]
